### ISSUE TITLE
package install failed

### ISSUE THREAD

**Issue by tdiprima** [camicroscope/ViewerDockerContainer#61]
### Problem
Got an error on line 9 of the Dockerfile during build:
`E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-bin_2.4.7-1ubuntu4.15_amd64.deb  404  Not Found [IP: 91.189.88.162 80]`

It looks like Apache has upgraded and deleted the old version of apache2 (apache2-bin_2.4.7-1ubuntu4.16_amd64.deb).  Still, I'm surprised `RUN apt-get -q -y install apache2` wasn't pulling the new version.

### Solution
To avoid apt-get cache issue, I'm doing an apt-get clean all.
Next, I do an apt-get update.
And finally, run the `apt-get -q -y install apache2`
And it works.

**Comment by tdiprima** [comment]
I recommend doing the `update` after `dist-upgrade`.
Because the build failed again, this time on `libtool` (line 32), because Ubuntu updated the package and removed the old one.
@sharmaashish I created another pull request.  May I please have write access to this repo?

**Comment by sharmaashish** [comment]
Done
