### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by tdiprima** [camicroscope/ViewerDockerContainer#71]
Security's config.ini already has an entry for `api_key`.  So either ViewerDockerContainer's run.sh needs to be updated to change that entry, not add it; OR config.ini needs to be updated with that line removed.

Ref: #64

**Comment by birm** [comment]
I've removed it. In any case, config.ini probably shouldn't be a committed file, and generated by the container if any customization is needed. For now, I'll let it be, though.

**Comment by tdiprima** [comment]
Ok.  Also &mdash; when I click the "Signup User" button, it still takes me back to the Login screen.  Even though I generated the api_key and set it in config.ini in the container.

Now... the client_id and client_secret values in `security_config.php` are not updated upon entering them in config.ini.  They probably should be, right?

**Comment by tdiprima** [comment]
Or maybe [request.php?doAction=signUp](request.php?doAction=signUp) isn't working.  Creating new issue in Security repo.
